apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: namespace1
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 'Hola desde NGINX con ConfigMap!';
        }
      }
    }
