apiVersion: apps/v1
kind: Deployment
metadata:
  name: back1-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back1
  template:
    metadata:
      labels:
        app: back1
    spec:
      containers:
        - name: back1-container
          image: back1:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
