apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./manifests
    repoURL: https://github.com/bastianparedes/k8
    targetRevision: HEAD
  project: default
