apiVersion: apps/v1
kind: Deployment
metadata:
  name: back2-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back2
  template:
    metadata:
      labels:
        app: back2
    spec:
      containers:
        - name: back2-container
          image: back2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
