apiVersion: v1
kind: Service
metadata:
  name: back2-service
  namespace: default
spec:
  selector:
    app: back2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
