# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nginx-config
#   namespace: namespace1
# data:
#   nginx.conf: |
#     events {}
# 
#     http {
#       server {
#         listen 80;
# 
#         location ^~ /path1/ {
#           rewrite ^/path1(/.*)?$ $1 break;
#           proxy_pass http://back1-service.namespace1.svc.cluster.local;
#           proxy_set_header Host $host;
#           proxy_set_header X-Real-IP $remote_addr;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header X-Forwarded-Proto $scheme;
#         }
# 
#         location ^~ /path2/ {
#           rewrite ^/path2(/.*)$ $1 break;
#           proxy_pass http://back2-service.namespace2.svc.cluster.local;
#           proxy_set_header Host $host;
#           proxy_set_header X-Real-IP $remote_addr;
#           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#           proxy_set_header X-Forwarded-Proto $scheme;
#         }
#       }
#     }
# 